# Generated by Django 6.0.3 on 2026-06-10 04:12

import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labreport',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='file_mime_type',
            field=models.CharField(default='application/octet-stream', max_length=50),
        ),
        migrations.AddField(
            model_name='labreport',
            name='file_size',
            field=models.IntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='labreport',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Processing time in seconds', null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='doctor_questions',
            field=models.JSONField(blank=True, default=list, help_text='Questions to ask doctor'),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='file',
            field=models.FileField(upload_to='%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='explanation_english',
            field=models.TextField(blank=True, help_text='English explanation'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='explanation_urdu',
            field=models.TextField(blank=True, help_text='Urdu explanation'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='is_abnormal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['user', '-created_at'], name='reports_lab_user_id_57065f_idx'),
        ),
        migrations.AddIndex(
            model_name='labreport',
            index=models.Index(fields=['status'], name='reports_lab_status_b66a71_idx'),
        ),
        migrations.AddIndex(
            model_name='testresult',
            index=models.Index(fields=['report', 'is_abnormal'], name='reports_tes_report__cabd4f_idx'),
        ),
    ]
